### ISSUE TITLE
vec_between()

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/funs#26]
I think vctrs has all the tools (vec_proxy_compare, ...) for a generic implementation of between, e.g. 

``` r
library(vctrs)

vec_between <- function(x, left, right) {
  vec_compare(x, left) >= 0 & vec_compare(x, right) <= 0
}

vec_between(1:10, 0, 11)
#>  [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
vec_between(1:10, 0, 11:20)
#>  [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
vec_between(1:10, -(1:10), 11)
#>  [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
vec_between(1:10, -(1:10), 11:20)
#>  [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE

vec_between(letters[11:20], "a", "z")
#>  [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
```

<sup>Created on 2018-12-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by jayqi** [comment]
Hello,

I was told in https://github.com/tidyverse/dplyr/issues/5122 that this is the place to track when `between` for character vectors will be available in dplyr. I see that this issue is closed and that an implementation is merged into the `funs` package. It's not clear to me what the `funs` package is, and when/if I should expect it to be available to general public users, e.g., on CRAN. Any more information would be very helpful.

Thanks!
